-- -------------------------------------------------------------
-- TablePlus 4.0.2(374)
--
-- https://tableplus.com/
--
-- Database: business_mappings
-- Generation Time: 2021-08-11 17:01:53.1840
-- -------------------------------------------------------------


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


INSERT INTO `required_documents` (`id`, `document_title`, `document_short_name`, `document_remarks`, `document_status`) VALUES
(1, 'CNIC', '', '', 'Active'),
(2, 'Passport Copy', '', '', 'Active'),
(3, 'SECP Certificate', '', '', 'Active'),
(4, 'Building Plan', '', '', 'Active'),
(5, 'Tax Certificate', '', '', 'Active'),
(6, 'Partnership Deed', '', '', 'Active'),
(7, 'Challan Form', '', '', 'Active'),
(8, 'Memorandum of Association', '', '', 'Active'),
(9, 'Articles of Association', '', '', 'Active'),
(10, 'Firm Registration Certificate', '', '', 'Active'),
(11, '1.	Layout plan of factory premises. 2.	Photocopy of registry of land/factory (if you are owner). 3.	Photocopy of lease agreement (if you are tenant). 4.	Photocopy of partnership deed along-with list of partners giving father\'s name, permanent address, etc', '', '', 'Active'),
(12, 'Test Document Checklist - Bill', 'BIll Doc', '', 'Active'),
(13, 'Test DOC Upload', '', '', 'Active'),
(14, 'NEW TEST EDIT UP', '', '', 'Active'),
(15, 'EOBI registration Card, Payslips for the last one year, Employment Certificate, contribution certificate', '', '', 'Active'),
(16, '1.	Application to ETO on office Letter pad. 2.	Copy of CNIC of tax payer. 3.	National Tax Number (NTN) 4.	Proof of SECP Registration/Registration in Registrar Office/Any authorized Registration. 5.	Leasing Agreement of the Office. 6.	Monthly Salary Sheet ', '', '', 'Active'),
(17, '1. Biometric verification of applicant 2. CNIC copy 3.	Application for the registration 4.Proof of purchase, 5.Proof of residence', '', '', 'Active'),
(18, 'Feasibility Report along with all relevant documentary evidences', '', '', 'Active'),
(19, 'Employees list', '', '', 'Active'),
(20, '- Application form (duly filled in and signed with stamp)', '', '', 'Active'),
(21, 'Copy of registration of company duly attested by respective Pak Embassy.', '', '', 'Active'),
(22, 'Copy of Article of Memorandum of Association duly attested by Pak Embassy.', '', '', 'Active'),
(23, 'Copy of Resolution/Authority letter of the company to establish Branch/Liaison Office in Pakistan.', '', '', 'Active'),
(24, 'Company Profile.', '', '', 'Active'),
(25, 'CV of Designated person authorized to act on behalf of the company + Passport copy/CNIC.', '', '', 'Active'),
(26, 'Copy of contract agreement (in case of Branch office only).', '', '', 'Active'),
(27, 'One original set and five copies are requested of all above documents', '', '', 'Active'),
(28, 'Original Fee Slip', '', '', 'Active'),
(29, 'Companies download application forms:-', '', '', 'Active'),
(30, 'Covering letter of the company', '', '', 'Active'),
(31, 'Application form duly filled in (airport entry Pass form) (in triplicate).', '', '', 'Active'),
(32, 'Certified copy of latest audited financial statement indicating equity investment of the company.', '', '', 'Active'),
(33, 'Security Clearance Form (in triplicate)', '', '', 'Active'),
(34, 'Copy of each CNIC', '', '', 'Active'),
(35, 'Departmental card', '', '', 'Active'),
(36, 'Old Airport Entry Pass.(if any)', '', '', 'Active'),
(37, 'Security Clearance from SSP, Special Branch.', '', '', 'Active'),
(38, 'Colour Photograph (5 Nos)', '', '', 'Active'),
(39, 'Original Bank Receipt of Airport Entry Pass processing fee US$100 (equal in Pak rupees)', '', '', 'Active'),
(40, 'Declaration Form', '', '', 'Active'),
(41, 'provision of list of employees and approval by competent authority', '', '', 'Active'),
(42, 'Application for assessment of bank guarantee and approval by competent authority', '', '', 'Active'),
(43, 'NOC required from Tourism Department', '', '', 'Active'),
(44, 'NOC required from District Health authority', '', '', 'Active'),
(45, 'NOC required from Civil Defence', '', '', 'Active'),
(46, 'NOC required from Police department', '', '', 'Active'),
(47, 'NOC required from concerned DC', '', '', 'Active'),
(48, 'NOC required from Environment department', '', '', 'Active'),
(49, 'Brief profile of the sponsors/franchise of concerned hotel', '', '', 'Active'),
(50, 'Condition of 4-5 star hotel', '', '', 'Active'),
(51, 'Documents regarding financial & corporate status of applicant', '', '', 'Active'),
(52, 'Undertakings by applicant regarding responsibility of abiding by all laws/rules ', '', '', 'Active'),
(53, 'Issuance of public notice for any objection', '', '', 'Active'),
(54, 'Payment of all relevant fees/taxes', '', '', 'Active'),
(55, 'Map/lay out plan of premises duly approved by the competent authority', '', '', 'Active'),
(56, 'NOC from Ministry of Industry GOP for explosive', '', '', 'Active'),
(57, 'Application, CNIC copy, Fee Challan, Field inspection report by inspector, Recommendation of Deputy Controller (W&M), Approval of Controller (W&M)', '', '', 'Active'),
(58, '1. Application with complete mailing address 2. Certified copy of CNIC 3. Certified copy of certificate of incorporation along with AOA & MOA,  Feasibility report, Financial statement, Detail of proposed land or machinery, Capacity , Timeframe ', '', '', 'Active'),
(59, 'CNIC copy, Fee Challan, Boiler Drawing, Concerned Engineer details', '', '', 'Active'),
(60, ' Application with complete mailing address, CNIC copy, Copy of certificate of incorporation along with AOA & MOA, Feasibility report, Financial statement, Detail of proposed land or machinery, Capacity , Timeframe, NOC from concerned departments(if any)', '', '', 'Active'),
(61, 'Surety Bond of Rs.50000', '', '', 'Active'),
(62, 'Promisery Note for equal to the amount of average 3 month production of factory', '', '', 'Active'),
(63, 'D-3 bond on a prescribed form to pledge the property ', '', '', 'Active'),
(64, 'undertaking regarding payment of all due at distillerys and salaries of staff posted', '', '', 'Active'),
(65, 'Undertaking to provide residence to the excise posted staff at distillery', '', '', 'Active'),
(66, 'Copy of CNIC', '', '', 'Active'),
(67, '2 Passport size photographs', '', '', 'Active'),
(68, 'Copy of Registration Book', '', '', 'Active'),
(69, 'Fitness Certificate', '', '', 'Active'),
(70, 'Affidavit ', '', '', 'Active'),
(71, 'Third Party Insurance', '', '', 'Active'),
(72, 'Passenger Guarantee', '', '', 'Active'),
(73, '2 Passport size photograph', '', '', 'Active'),
(74, 'Registration Book Copy', '', '', 'Active'),
(75, 'Application on Letter Pad duly signed by Owner', '', '', 'Active'),
(76, 'FARD of Land or rental deed', '', '', 'Active'),
(77, 'Detail of Machinery equipment and technical staff', '', '', 'Active'),
(78, 'NOC from TMA regarding encroachment ', '', '', 'Active'),
(79, 'passport size photographs', '', '', 'Active'),
(80, 'detail of staff', '', '', 'Active'),
(81, 'At least 4 Trucks owned by Owner', '', '', 'Active'),
(82, 'Factory Visit ', '', '', 'Active'),
(83, 'Valid License from PSQCA & EDB', '', '', 'Active'),
(84, 'Product Inspection by the Committee  ', '', '', 'Active'),
(85, 'Fard Malkiet owned by the Owner for at least 4 canals', '', '', 'Active'),
(86, 'NOC from TMA', '', '', 'Active'),
(87, 'Approved Map from TMA', '', '', 'Active'),
(88, 'NOC from Revenue Department ', '', '', 'Active'),
(89, 'NOC from Traffic Police', '', '', 'Active'),
(90, 'NOC from Police', '', '', 'Active'),
(91, 'NOC from Highways ', '', '', 'Active'),
(92, 'NOC from Building Department ', '', '', 'Active'),
(93, 'Inspection Report from DRTA', '', '', 'Active'),
(94, 'Witness Form', '', '', 'Active'),
(95, 'Pakistan Engineering Council Registration', '', '', 'Active'),
(96, 'Previuos Year Registration', '', '', 'Active'),
(97, 'Following documents are required for the registration case that mentioned in SOP\'s 2.2.	DOCUMENTS TO BE ACCOMPANIED WITH THE REGISTRATION CASE:', '', '', 'Active'),
(98, 'Test Report from LEC ', '', '', 'Active'),
(99, 'Memorandum of Article of Association (In case of limited company)', '', '', 'Active'),
(100, 'Certificate of Stability', '', '', 'Active'),
(101, 'List of Workers', '', '', 'Active'),
(102, 'List of Machinery', '', '', 'Active'),
(103, 'Layout Plan', '', '', 'Active'),
(104, 'As per the RE Policy, sponsor wishing to undertake a project at raw site would be required to submit a detailed proposal to the AEDB, which must be incompliance with applicable policy guidelines and include, at a minimum, the following:   ', '', '', 'Active'),
(105, 'i.	Statement of qualification of project sponsor, Listing relevant corporate experience, Personal and Financial Capacity', '', '', 'Active'),
(106, 'ii.	Project Name and ARE technology classification (i.e. wind, solar, Bagasse etc', '', '', 'Active'),
(107, 'iii.	Proposed Project Location (including geographical or GPS coordinates', '', '', 'Active'),
(108, 'iv.	Proposed net installed capacity (MW) and expected annual energy output (MWh);', '', '', 'Active'),
(109, 'v.	Basic outline of plant and structures', '', '', 'Active'),
(110, 'vi.	Summary implementation plan, Committing milestones for project preparation, Implementation and Completion dated', '', '', 'Active'),
(111, 'vii.	Estimated distance from the nearest 132 kV or 11 kV line or grid station', '', '', 'Active'),
(112, 'viii.	Last three years audited financial reports of Project Sponsor ', '', '', 'Active'),
(113, 'Following documents required to process the request of the Project Sponsor for approval of Feasibility Study', '', '', 'Active'),
(114, '•	Detailed feasibility study including but not limited to Technical and Financial information/calculations of the project;', '', '', 'Active'),
(115, 'Approval of NOC by EPA from relevant provincial government', '', '', 'Active'),
(116, '•	Approval of Grid Interconnection Study by NTDCL/ relevant DISCOs', '', '', 'Active'),
(117, '•	Any other information /documents as required by the POE', '', '', 'Active'),
(118, 'Following documents required to process the request of the Project Sponsor for issuance of Letter of Support:', '', '', 'Active'),
(119, 'i.	No Objection Certificate (NOC) from Environmental Protection Agency, Provincial Department;', '', '', 'Active'),
(120, 'ii.	Approval of Grid Interconnection Study Report from NTDCL/ relevant DISCO;', '', '', 'Active'),
(121, 'iii.	Issuance of Consent to Purchase Power by CPPA-G;', '', '', 'Active'),
(122, 'iv.	Issuance of Power Acquisition Request (PAR) by the CPPA (G);', '', '', 'Active'),
(123, 'v.	Generation Licence by NERPA;', '', '', 'Active'),
(124, 'vi.	Project tariff by NEPRA;', '', '', 'Active'),
(125, 'vii.	Certificate of incorporation of “SPV” by Securities and Exchange Commission of Pakistan; ', '', '', 'Active'),
(126, 'viii.	Memorandum and Articles of Association of SPV', '', '', 'Active'),
(127, 'ix.	Form A,3, 21, 29 of SPV', '', '', 'Active'),
(128, '1.	Letter of Support (LOS) from AEDB', '', '', 'Active'),
(129, '2.	Submission of executed Energy Purchase Agreement (EPA) with Power Purchaser (CPPA-G/DISCOs)', '', '', 'Active'),
(130, '3.	Execute Implementation Agreement (IA) with AEDB', '', '', 'Active'),
(131, '4.	Submission of executed Direct EPA with Power Purchaser (CPPA-G/DISCOs)', '', '', 'Active'),
(132, '5.	Execute Direct IA with AEDB', '', '', 'Active'),
(133, '6.	Submission of Financing Documents to AEDB ', '', '', 'Active'),
(134, '7.	Term sheet approval from AEDB', '', '', 'Active'),
(135, '8.	Confirmation of LC by Power Purchaser (CPPA-G/DISCOs)', '', '', 'Active'),
(136, '9.	Confirmation letter from Lender(s) that all condition precedents (CPs) for disbursement of funds have been met or waived', '', '', 'Active'),
(137, '10.	Issuance of GoP Guarantee by AEDB', '', '', 'Active'),
(138, '*For Projects to whom land has been leased by provincial government, the land Land Lease Agreement would be required.', '', '', 'Active'),
(139, 'Letter of Support(LOS', '', '', 'Active'),
(140, 'Term sheet by Lender(s) in compliance of NEPRA Tariff', '', '', 'Active'),
(141, '1.	Security Clearance Performa', '', '', 'Active'),
(142, '2.	Computer Performa', '', '', 'Active'),
(143, '3.	Bio data Form', '', '', 'Active'),
(144, 'An Oil Marketing Company, having license from Oil & Gas Regulatory Authority, shall apply for No Objection Certificate (NOC) from Ministry of Defence from security point of view through the office of Directorate General (Oil), Ministry of Energy (Petroleu', '', '', 'Active'),
(145, 'No construction shall commence on the storage site prior to obtaining the NOC from Ministry of Defence', '', '', 'Active'),
(146, 'The application for NOC must contain following information/documents', '', '', 'Active'),
(147, 'Exact location of the proposed project site mentioning: i.	Name of Village/Chak No. ii.	Khewat No. iii.	Khatooni No. iv.	Killa No. v.	Mouza vi.	Tehsil /District. (10 copies)', '', '', 'Active'),
(148, 'Executive Summary of the Project. (10 copies)', '', '', 'Active'),
(149, 'Geodatic Parameters (showing exact Latitudes and 	Longitudes with distances from various international boundaries) (10 copies)', '', '', 'Active'),
(150, 'Satellite Imagery (10 copies)', '', '', 'Active'),
(151, 'Camouflage Scheme of Storage Tanks (10 copies)', '', '', 'Active'),
(152, 'Statement of Area site plan (10 copies)', '', '', 'Active'),
(153, 'Site digit coordinates (Degree, Minute, Second) and site elevation duly verified from Survey of Pakistan (10 copies)', '', '', 'Active'),
(154, 'Height of infrastructure (10 Copies)', '', '', 'Active'),
(155, 'Plot Plan (33\" x 23.5\") (04 SETS)', '', '', 'Active'),
(156, 'CD containing complete case (04)', '', '', 'Active'),
(157, 'Security Clearance Proforma ', '', '', 'Active'),
(158, 'Security Clearance Computer Proforma', '', '', 'Active'),
(159, 'Bio Data Form ', '', '', 'Active'),
(160, 'Copy of Passport', '', '', 'Active'),
(161, 'DOCUMENTS REQUIRED FOR PROCESSING OF GRANT/RENEWAL OF C.M. LICENSE AS PER PSQCA ACT-VI OF 1996', '', '', 'Active'),
(162, '1. Form for Grant & Renewal Application', '', '', 'Active'),
(163, '2.	List of machinery and their details.', '', '', 'Active'),
(164, '3.	Copies of Income Tax Registration NTN and assessment of proprietor/Director Organization.', '', '', 'Active'),
(165, '4.	GST/NTN Certificates.', '', '', 'Active'),
(166, '5.	Copies of educational qualification certificates of the quality control staff of the unit.', '', '', 'Active'),
(167, '6.	Calibration Certificates Lab equipment’s.', '', '', 'Active'),
(168, '7.	Undertaking for promotion of New PS Logo.', '', '', 'Active'),
(169, '8.	Food Grade Packing Material Certificates.', '', '', 'Active'),
(170, '9.	Copy of Trade Mark Registration.', '', '', 'Active'),
(171, '10.	Copy of CNIC.', '', '', 'Active'),
(172, '11.	Copy of Process Flow Chart. ', '', '', 'Active'),
(173, '12.	Plant Layout.', '', '', 'Active'),
(174, '13.	License Agreement/Undertaking.', '', '', 'Active'),
(175, 'An application for incorporation of company along with specified fee', '', '', 'Active'),
(176, 'memorandum', '', '', 'Active'),
(177, '(ii) articles where required;', '', '', 'Active'),
(178, '(iii) copies of valid NIC/NICOP (national identity card/ national identity card for overseas Pakistanis) of the subscribers/ directors/chief executive officer or copies of valid Passport in case of a foreigner; ', '', '', 'Active'),
(179, '(iv) in case of a single member company copy of valid NIC/NICOP of nominee or copy of valid Passport in case of a foreigner; ', '', '', 'Active'),
(180, '(v) copy of NIC of witness in case of physical filing of application;', '', '', 'Active'),
(181, '(vi) in case of physical application, authority letter on stamp paper of requisite value in favour of any one of the subscribers or registered intermediary, authorizing him to file documents for incorporation of company on behalf of subscribers, make corr', '', '', 'Active'),
(182, '(vii) NOC/Letter of Intent/ License (if any)/ approval letter of the relevant regulatory authority in case of specialized business as mentioned in regulation 4; ', '', '', 'Active'),
(183, '(viii) in case of physical application, original paid bank challan or other evidence of payment of fee specified in Seventh Schedule of the Act.', '', '', 'Active'),
(184, '(ix) copy of valid NIC/Passport of person duly authorized by the Board of directors of a body corporate which is a subscriber along with copy of Board resolution. In case of a subscriber which is a limited liability partnership, copy of valid NIC/ Passpor', '', '', 'Active'),
(185, '(x) in case the subscriber is a foreign company or a foreign body corporate, the profile of the company, detail of its directors, their nationality and country of origin, copy of its charter, statute or memorandum and articles etc., certified in the manne', '', '', 'Active'),
(186, 'An application to the registrar as per LLP-Form-III either online or in physical form for incorporation of LLP along with fee as per fee schedule', '', '', 'Active'),
(187, '(a) copies of National Identity Card (NIC) of the partners and of designated partners and in case of physical application, of witness to the documents and in case of foreigner, a copy of passport;', '', '', 'Active'),
(188, '(b) attested copy of LLP agreement duly executed by the partners, witnessed and notarized;', '', '', 'Active'),
(189, '(c) consent of designated partner (if any);', '', '', 'Active'),
(190, '(d) In case of physical application, original bank challan evidencing the payment of fee as specified in Fee Schedule;', '', '', 'Active'),
(191, '(e) any other information and document as required by the registrar', '', '', 'Active'),
(192, 'Application form', '', '', 'Active'),
(193, 'Authority Letter /Power of Attorney', '', '', 'Active'),
(194, 'Letter of intimation to other party', '', '', 'Active'),
(195, 'Copy of the Agreement', '', '', 'Active'),
(196, 'Demand draft/Pay order/cheque', '', '', 'Active'),
(197, 'Annual & Financial Report', '', '', 'Active'),
(198, 'List of dealers/distributors ( in case of template application)', '', '', 'Active'),
(199, 'List of Products', '', '', 'Active'),
(200, 'Any other relevant supporting document(s) pertaining to agreement', '', '', 'Active'),
(201, 'Contact name, address, phone number, fax number and email address of the applicant and the undertakings concerned', '', '', 'Active'),
(202, 'Full legal name of the merger parties', '', '', 'Active'),
(203, 'Type of notification', '', '', 'Active'),
(204, 'Type of transaction', '', '', 'Active'),
(205, 'Full details of transaction value', '', '', 'Active'),
(206, 'Payment of applicable processing fee', '', '', 'Active'),
(207, 'A full description of the business of the acquirer', '', '', 'Active'),
(208, 'A full description of the business of the target', '', '', 'Active'),
(209, 'Turnover of the acquirer', '', '', 'Active'),
(210, 'Turnover of the target', '', '', 'Active'),
(211, 'Rationale of the transaction', '', '', 'Active'),
(212, 'Ancillary restrictions', '', '', 'Active'),
(213, 'A full description of the relevant product market(s) in Section 2B', '', '', 'Active'),
(214, 'A full description of relevant geographic market (s ) in Section 2B ', '', '', 'Active'),
(215, 'Details of area(s) of overlap between the merger parties', '', '', 'Active'),
(216, 'Market Share of Acquire', '', '', 'Active'),
(217, 'Entry barriers, ', '', '', 'Active'),
(218, 'Whether the transaction meets the notification thresholds prescribed in Regulation 4', '', '', 'Active'),
(219, 'Name and contact details of at least 3 principal customers and competitors', '', '', 'Active'),
(220, 'Name and contact details of at least 3 principal customers and competitiors', '', '', 'Active'),
(221, 'Notification of the transaction in other countries', '', '', 'Active'),
(222, 'Copies of the most recent Annual report for the acquirer', '', '', 'Active'),
(223, 'Copy of the most recent Annual report for the target', '', '', 'Active'),
(224, 'Copy of the share purchase agreement or offer document', '', '', 'Active'),
(225, 'Organogram of the acquirer ', '', '', 'Active'),
(226, 'Organogram of the target', '', '', 'Active'),
(227, 'Equipment brochures', '', '', 'Active'),
(228, 'technical data sheet and filled application forms', '', '', 'Active'),
(229, 'PTA/ PEMRA forward the cases of applicants for frequency assignment/ site clearance etc. to FAB ', '', '', 'Active'),
(230, 'technical data sheet and test reports from accredited laboratories  ', '', '', 'Active'),
(231, 'Complete application forms and documents submitted to PTA', '', '', 'Active'),
(232, 'Statement of Allocation and Distribution of Workers\' Profit Participation Fund as per Annex-Ill duly verified by all four members of BOT', '', '', 'Active'),
(233, 'Signed \"Printed\" copy of the Annual Audited Accounts/Report of the Company', '', '', 'Active'),
(234, 'Signed copy of Annual Audited Accounts of W.P.P.F', '', '', 'Active'),
(235, 'Minutes of the meeting of Board of Trustees held for distribution of Workers\' Profit Participation Fund and its distribution among the workers for the relevant year(s)', '', '', 'Active'),
(236, 'Details of interest accrued on total Allocated Workers\' Profit Participation Fund and its distribution among workers and the left out amount as per Annex 111(A)', '', '', 'Active'),
(237, 'Names and addresses of Members of Board of Trustees', '', '', 'Active'),
(238, 'Challan in \"Original\" (Federal Treasury Challan) showing deposit left out amount in NBP/SBP under the head G-06304 Workers\' Welfare Fund', '', '', 'Active'),
(239, 'Name wise payment vouchers/sheets as per Annex III & III (A) with signature/stamp of BOT and I.D. Card Nos. of the workers duly verified (every page) by all four members of the Board of Trustees.', '', '', 'Active'),
(240, 'Old Airport Entry Pass (if any)', '', '', 'Active'),
(241, 'Application form alongiewith company letter dully forwarded by DGPC ', '', '', 'Active'),
(242, 'Original Fee receipt', '', '', 'Active'),
(243, 'Security Proforma', '', '', 'Active'),
(244, 'Copy of Valid Passport and valid visa', '', '', 'Active'),
(245, 'Certificate of incorporation', '', '', 'Active'),
(246, 'Form A of SECP', '', '', 'Active'),
(247, 'NTN Certificate of Company', '', '', 'Active'),
(248, 'NTN Certificates of Chief Executive and Directors', '', '', 'Active'),
(249, 'Copies of CNICs of Chief Executive and Directors', '', '', 'Active'),
(250, 'Form 21 of SECP (Certified by SECP)', '', '', 'Active'),
(251, 'Form 29 of SECP (Attested Latest)', '', '', 'Active'),
(252, 'Form 3 of SECP (Attested Latest)', '', '', 'Active'),
(253, 'Copies of passports of Chief Executive & Directors of the Company', '', '', 'Active'),
(254, 'Clearance Certificate from SECP about any Dispute', '', '', 'Active'),
(255, 'Financial Reports of last 03 years duly Audited by Chartered Accountant Firms (preferably QCR certified)', '', '', 'Active'),
(256, 'Certificate from State Bank of Pakistan that Company has not defaulted any Bank Loan', '', '', 'Active'),
(257, 'Verifiable certified documentary evidence of experience from the concerned quarters', '', '', 'Active'),
(258, 'Three sets of Application Forms with Attested documents.', '', '', 'Active'),
(259, 'Any other documents mentioned in the form, etc', '', '', 'Active'),
(260, 'Export Control (Licensing and Enforcement) Rules, 2009', '', '', 'Active'),
(261, 'Filled application form with requisite documents', '', '', 'Active'),
(262, 'Export Control (Licensing and Enforcement) Rules, 2009.', '', '', 'Active'),
(263, 'Filled Application Form', '', '', 'Active'),
(264, 'End User Certificate', '', '', 'Active'),
(265, 'MSDS', '', '', 'Active'),
(266, 'Copy of CNIC of Owner / Partner', '', '', 'Active'),
(267, 'Two Photographs', '', '', 'Active'),
(268, 'Membership Certificate of APGMJEA', '', '', 'Active'),
(269, 'Bank\'s Account Maintenance Certificate', '', '', 'Active'),
(270, 'Copy of NTN Certificate issued by FBR', '', '', 'Active'),
(271, 'Copy of Utility Bill', '', '', 'Active'),
(272, 'Two years Tax Return', '', '', 'Active'),
(273, 'Original Pay Order amounting Rs. 3000/-', '', '', 'Active'),
(274, 'Copy of Sales Tax Registration Certificate', '', '', 'Active'),
(275, 'Copy of Partnership Deed', '', '', 'Active'),
(276, 'Filled Form', '', '', 'Active'),
(277, 'Bill of Lending', '', '', 'Active'),
(278, 'Goods Declaration', '', '', 'Active'),
(279, 'Commercial Invoice', '', '', 'Active'),
(280, 'Approved Map of the School Building.', '', '', 'Active'),
(281, 'An attested Affidavit showing name of School, level, owner’s name.', '', '', 'Active'),
(282, 'Copy of Rent deed / Ownership deed.', '', '', 'Active'),
(283, 'Printed Prospectus and Admission Form.', '', '', 'Active'),
(284, 'Teachers Appointment order and their Testimonials.', '', '', 'Active'),
(285, 'Building Fitness Certificate from, Registered Engineer or Registered Architect', '', '', 'Active'),
(286, 'Rules & & Regulations of the Institution', '', '', 'Active'),
(287, 'Registration Certificate in case of NGO / Association / Body / Registered by Authority Joint Stock / Social Welfare Department. ', '', '', 'Active'),
(288, 'Company details', '', '', 'Active'),
(289, 'List of Responsible persons', '', '', 'Active'),
(290, 'Enlistment with any Stock Exchange', '', '', 'Active'),
(291, 'Total per year Demand', '', '', 'Active'),
(292, 'Utilization / use of Chemicals', '', '', 'Active'),
(293, 'List of Machinery installed in the unit', '', '', 'Active'),
(294, 'Copy of ownership / lease agreement', '', '', 'Active'),
(295, 'Copy of Sales Tax Registration', '', '', 'Active'),
(296, 'Copy of map of Premises', '', '', 'Active'),
(297, 'Annual Production of the firm', '', '', 'Active'),
(298, 'Chamber membership certificate', '', '', 'Active'),
(299, 'Total working strength', '', '', 'Active'),
(300, 'Year wise imports for the last three years', '', '', 'Active'),
(301, 'Copy of Stock Register having the entry of subject chemicals ', '', '', 'Active'),
(302, 'GSP/GMP Compliance Certificate ', '', '', 'Active'),
(303, 'Filled form IF-II, IF-III and IF-IV (Company’s details, name and quantity of Chemicals to be imported / exported/ distributed / sold, Stock position, Name of importer / exporter firm, Name of exporting country, Expected schedule for utilization, per annum', '', '', 'Active'),
(304, 'Filled Form IF-I', '', '', 'Active'),
(305, 'Filled Form IF-II and IF-IV', '', '', 'Active'),
(306, 'As per Regulation-3 read with Schedule-III of the NEPRA Licensing (Application and Modification Procedure) Regulations, 1999 ', '', '', 'Active'),
(307, 'Each and Every page of the case should be duly marked numbered and attached by the concerned college principal or management of the college', '', '', 'Active'),
(308, 'Specimen signature of concerned college principal in triplicate', '', '', 'Active'),
(309, 'Detail of specific subject/ Discipline for which registration is required/ recommended by the inspection committee.', '', '', 'Active'),
(310, 'Original bank challan of registration fee deposited', '', '', 'Active'),
(311, 'Certificate of Registration of Qualified Person', '', '', 'Active'),
(312, 'Copy of Certificate of Registration of Category B Pharmacist', '', '', 'Active'),
(313, 'Certificate of Registration of Qualified Pharmacist by Punjab Medical Faculty before 2007', '', '', 'Active'),
(314, '(a)	the original copy of the Treasury Challan pertaining to the deposit of such application fee as is notified by the Government from time to time', '', '', 'Active'),
(315, '(b)	in the case of a partnership firm, an authenticated copy of the partnership deed duly registered with the Registrar of Firms concerned', '', '', 'Active'),
(316, '(c)	 in the case of a company, a verified copy each of the Memorandum and Articles of Association and Certificate of Incorporation;', '', '', 'Active'),
(317, '(d)	fifteen copies of the map duly signed by the applicant, showing the boundaries of the area in respect of which the licence or lease is applied for.  The map shall be prepared from the Survey of Pakistan Maps of Scale 1:50,000 or nearest scale availabl', '', '', 'Active'),
(318, '(e)	evidence of financial status of the applicant in the manner as may be prescribed by the Licensing Authority from time to time', '', '', 'Active'),
(319, '(a)	the original copy of the Treasury Challan pertaining to the deposit of such registeration fee as is notified by the Government from time to time', '', '', 'Active'),
(320, '(b)   Certificate of Diploma in Mining Surveying from Government Institutues', '', '', 'Active'),
(321, '(c)    Experience letter', '', '', 'Active'),
(322, '(d)    Survey Comptency Certificate issued by Chief Inspectorate of Mines', '', '', 'Active'),
(323, 'Chamber of Commerce Certificate', '', '', 'Active'),
(324, 'FBR Certificate', '', '', 'Active'),
(325, 'NTN Certificate', '', '', 'Active'),
(326, 'Company Profile', '', '', 'Active'),
(327, 'Request from the exporter mentioning type, year of production, quantity, price and destination of the tobacco exported', '', '', 'Active'),
(328, 'Registration with PTB', '', '', 'Active'),
(329, 'Goods Declaration Certificate (G.D)', '', '', 'Active'),
(330, 'Form E', '', '', 'Active'),
(331, 'Bill of Lading (B/L)', '', '', 'Active'),
(332, 'Certificate of Chamber of Commerce', '', '', 'Active'),
(333, 'NTN.', '', '', 'Active'),
(334, 'Original Invoice', '', '', 'Active'),
(335, 'Company Profile and complete details as per format', '', '', 'Active'),
(336, 'Application Form-2', '', '', 'Active'),
(337, 'Bank Challan of Rs.5000/- (Original)', '', '', 'Active'),
(338, 'Sole Proprietor Partnership deed or Article and Memorandum of Association', '', '', 'Active'),
(339, 'Good Conduct Certificate', '', '', 'Active'),
(340, 'Income Tax Certificate', '', '', 'Active'),
(341, 'Bio-Data of Applicant(s)', '', '', 'Active'),
(342, 'Bio-Data of Applicant’s Father/Husband', '', '', 'Active'),
(343, 'Specimen Signature of Applicant/Managing Director', '', '', 'Active'),
(344, 'Name of two persons who know the applicant(s)', '', '', 'Active'),
(345, 'Five Photographs (Passport size) of applicant(s)', '', '', 'Active'),
(346, 'Bank Certificate', '', '', 'Active'),
(347, 'Bank Account transaction statement or Property Deed', '', '', 'Active'),
(348, 'Undertaking on Stamp Paper valued Rs.50/-', '', '', 'Active'),
(349, 'Performance of OEP under whom the applicant worked (if any)', '', '', 'Active'),
(350, 'FORM PR-01  ', '', '', 'Active'),
(351, 'DULLY FILLED FORM-III ', '', '', 'Active'),
(352, 'ATTESTED COPIES OF CETIFICATES', '', '', 'Active'),
(353, 'FEE BANK DRAFT', '', '', 'Active'),
(354, 'PHOTOGRAPHS ', '', '', 'Active'),
(355, 'Copy of CNIC of Applicant', '', '', 'Active'),
(356, 'Ownership Deed/ Tenant Deed', '', '', 'Active'),
(357, 'Electric Inspector Report  ', '', '', 'Active'),
(358, 'Application form alogwith documents', '', '', 'Active'),
(359, 'Original Certificate legalized Pharmaceutical and of Product as per WHO format for applied product OR Original legalized certificate and GMP of new manufacturing certificate site with free sale from body of country of  origin. ', '', '', 'Active'),
(360, 'Sole Agency Agreement with complete contact detail of exporter. (For imported Biological Drugs only)', '', '', 'Active'),
(361, 'Biosimilarity study data as per WHO format (Only for Imported Human Biological Drugs of rDNA origin)', '', '', 'Active'),
(362, 'Bio-similarity study data as specified in 278 th meeting of Registration (Only for Board Local Human Biological Drugs of rDNA origin)', '', '', 'Active'),
(363, 'Copy of Drug Sale License Imported (For Biological  Drugs)', '', '', 'Active'),
(364, 'Copy of Drug Manufacturing License (DML) (For Local  Biological Drugs)', '', '', 'Active'),
(365, 'As per mentioned in Application Forms', '', '', 'Active'),
(366, 'Original Bank Challan of Registration Fee/Inspection fee deposited in the National Bank of Pakistan under the Head of Account \"C-02818-EDUCATION-OTHERS\" amounting to Rs. 10000+2000=12000/- in case of new Registration and Rs.2000/- in case of Extension', '', '', 'Active'),
(367, 'Verification of Bank Challan of Registration Fee/ Inspection Fee (after depositing the amount in the National Bank of Pakistan or State Bank of Pakistan) from the concerned District Accounts Office/ Treasury Office', '', '', 'Active'),
(368, 'Original Bank deposit slip of Refundable Security to be deposited in the National Bank of Pakistan Punjab Civil Seretariate Branch Lahore, under the Bank Account No. 006484-5 TITLE OF ACCOUNT: DIRECTOR PUBLIC INSTRUCTION (COLLEGES) PUNJAB,LAHORE amount...', '', '', 'Active'),
(369, 'Re-submit the same in the light of revised approved criteria for introduction of BS-4 year Program in Public and Private Sector Colleges in the Punjab alongwith the proformas duly filled in all respect, in accordance with the timeline calendar for proc...', '', '', 'Active'),
(370, 'College Management Information System (CMIS) form duly signed by the Principal & countersigned by the DE(C)/DDC Concerned (in duplicate).', '', '', 'Active'),
(371, 'Security arrangement certificate regarding SOPs duly countersigned by the Deputy Director (C).', '', '', 'Active'),
(372, 'Copy of latest extension certificates in case of extension in registration', '', '', 'Active'),
(373, 'GROUP WISE STAFF STATEMENT OF Teaching Staff Including Principal, Librarian & Lecturer in Physical Education (DPE) according to the sample available in Registration Booklet. (only male staff members are allowed to teach in male colleges and only female...', '', '', 'Active'),
(374, 'Building Fitness Certificate issued by the Govt. Building Department', '', '', 'Active'),
(375, 'Hygienically Fitness Certificate/Sanitation Certificate issued by the Govt. Health Department only.', '', '', 'Active'),
(376, 'Facility of play ground or certificate/permission to use play ground issued by the Head of any corporation or a private club/stadium for the students of the college(which registration is applying)', '', '', 'Active'),
(377, 'Attested copy of certificate of registration of the Society/ Corporate/ Company/ Trust along with a copy of its Memorandum under which the institute is being run.', '', '', 'Active'),
(378, 'A Letter from the Society/Corporate/Company/Trust on its letter pad that this institute is working under their governing body.', '', '', 'Active'),
(379, 'Copy of Franchise Certificate in case of Franchisee of any Group of Colleges.', '', '', 'Active'),
(380, 'Copy of Ownership/Rent Deed along with a  copy of Fard or PT-10 of Property Tax or any other proof of Ownership of property.', '', '', 'Active'),
(381, 'Map of Building (Designed by the Architect duly signed & stamp)', '', '', 'Active'),
(382, 'Staff statement of non-teaching employees according to the sample available in the book-let.', '', '', 'Active'),
(383, 'Comparative statements of fee-structure in case of extension in registration.', '', '', 'Active'),
(384, 'Copies of appointment orders of all the teaching and non teaching staff.', '', '', 'Active'),
(385, 'Copies of last degree (M.A/M.Sc. & M.Ed.) of Teaching Staff only.', '', '', 'Active'),
(386, 'Detail of Labs for Science Subjects.', '', '', 'Active'),
(387, 'Affidavit for no Co-Education according to the sample available in the booklet on stamp paper duly attested by the oath Commissioner.', '', '', 'Active'),
(388, 'Class wise and teacher wise Time table showing class rooms.', '', '', 'Active'),
(389, 'Statement of present enrollment and proposed enrollment.', '', '', 'Active'),
(390, 'Detailed list of library books with accession number.', '', '', 'Active'),
(391, 'Registration BOOK-LET duly filled in all respects.', '', '', 'Active'),
(392, 'Attested Photocopy of the CNIC of the OWNER of the College or Institution.', '', '', 'Active'),
(393, 'College E-Mail Address', '', '', 'Active'),
(394, 'AIRCRAFT OWNERSHIP DETAILS, LEASE AGREEMENT ETC.', '', '', 'Active'),
(395, 'Request for Issuance of USER ID on Letter Head ', '', '', 'Active'),
(396, '  Visiting Card and Two Photographs ( Passport Size) ', '', '', 'Active'),
(397, 'WeBoc External User Registration Form ', '', '', 'Active'),
(398, 'NADRA Verification ', '', '', 'Active'),
(399, 'National Tax Number Certificate ', '', '', 'Active'),
(400, 'Sales Tax Registration Certificate or IRIS-14 ( 1)', '', '', 'Active'),
(401, 'IRS-181 ( Order to grant / refuse modification to Registration on application ', '', '', 'Active'),
(402, 'Valid Chamber of Commerce Certificate ', '', '', 'Active'),
(403, 'Bussiness Office premises current utility bill ', '', '', 'Active'),
(404, 'Bank Account Maintenance Certificate of Firm with authorised signature and personal account stamp ', '', '', 'Active'),
(405, 'Bank Statement Current Six months with  with authorised signature and personal account stamp ', '', '', 'Active'),
(406, 'Active tax payers list ( ATL) Sales Tax and Income Tax', '', '', 'Active'),
(407, 'Online NTN/STRN inquiry ( Principal activity importer /exporter) ', '', '', 'Active'),
(408, 'Property Documents premises/office/ valid rent agreement with photocopy of landlord / CNIC copy ', '', '', 'Active'),
(409, 'Undertaking on stamp paper RS. 100', '', '', 'Active'),
(410, 'Bank receipt of pay order/ cash deposit Rs. 500 Importer /exporter name ', '', '', 'Active'),
(411, 'Available in Relevant Regulations', '', '', 'Active'),
(412, 'Bill of Lading, Invoice, CNIC Undertaking etc.', '', '', 'Active'),
(413, 'details mentioned in relevant forms and PAK/908', '', '', 'Active'),
(414, 'https://www.pnra.org/license_forms.html', '', '', 'Active'),
(415, 'Annexure A-E as per schedule', '', '', 'Active'),
(416, 'CNIC, SECP Certification, NTN etc.', '', '', 'Active'),
(417, ' The site plan of the proposes export oriented unit indicating the location of the premises and the details of the total area, covered area and manufacturing area and separate storage areas for manufactured goods, factory rejects and wastages;', '', '', 'Active'),
(418, 'National Tax Number certificate;', '', '', 'Active'),
(419, 'banker’s certificate, directly forwarded by the bank to the Collector in a sealed envelope, regarding financial transactions of the applicant during the last two years;', '', '', 'Active'),
(420, 'Memorandum and Articles of Association in the case where the applicant is registered under the Companies Ordinance, 1984 (XLVII of 1984), or partnership deed if it is a partnership firm;', '', '', 'Active'),
(421, ' Copy of the national identity card of owner and directors of the company;', '', '', 'Active'),
(422, 'general bond 2 [equal to the amount of duty and taxes] in the form set out in Appendix-II;', '', '', 'Active'),
(423, ' Lease or tenancy agreement with the written permission from the landlord to use the premises as an export oriented unit for a period of at least two years;', '', '', 'Active'),
(424, 'Certificate from supplier of fire fighting equipment installed in the premises regarding its validity date;', '', '', 'Active'),
(425, 'Comprehensive insurance policy covering all risks such as fire, burglary, riots, strikes, malicious damage and allied perils, issued by an insurance company having paid up capital not less than Rs.120 million, registered with  the Controller of Insurance,', '', '', 'Active'),
(426, 'An undertaking by an insurance company duly approved by the Controller of Insurance, Ministry of Commerce, on the stamp paper undertaking that- (i) Full premium under the aforesaid insurance policy has been duly received; (ii) In case the licensee does no', '', '', 'Active'),
(427, 'recommendations of the relevant representative trade association, or Chamber of Commerce and Industry, or Trade Development Authority of Pakistan; and', '', '', 'Active'),
(428, 'details of the type of machinery installed.', '', '', 'Active'),
(429, '(Yes)  SRO 450(I)/2001 dated 18.06.2001 and ( Copy Attached)', '', '', 'Active'),
(430, 'Annex A on Company\'s letter head', '', '', 'Active'),
(431, 'CNIC of applicant', '', '', 'Active'),
(432, 'All Pakistan Marble Industry Association (APMIA) valid membership certificate', '', '', 'Active'),
(433, 'Valid copy of NTN Certificate', '', '', 'Active'),
(434, 'Undertaking on the Stamp Paper', '', '', 'Active'),
(435, 'Bill of Lading (Machinery that is desired for exemption)', '', '', 'Active'),
(436, 'Packing list of container', '', '', 'Active'),
(437, 'Copy of brochure of concerned machinery / accessories', '', '', 'Active'),
(438, 'Processing fee of Rs.10,000 (Demand Draft / Pay Order) in the name of PASDEC', '', '', 'Active'),
(439, 'Invoice', '', '', 'Active'),
(440, 'GDs', '', '', 'Active'),
(441, 'Company\'s Letterhead', '', '', 'Active'),
(442, 'Valid Visas / Passports', '', '', 'Active'),
(443, 'NOC from Home Deptt, Ministry of Interior, Home Deptt Sindh', '', '', 'Active'),
(444, 'Process (B.P.F)', '', '', 'Active');


/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
